version: '3.8'

services:
  nginx:
    build: .\nginx_server\.
    container_name: nginx_server
    image: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .\nginx_server\nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]

  fastapi:
    build: .\fast_api\.
    container_name: motorway_api
    image: motorway_api
    env_file: .\fast_api\.env
    ports:
      - 7357:8000
    volumes:
      - .\fast_api:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
