version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_server
    image: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
