version: '3.8'
services:
  fastapi:
    build: .
    env_file: .env
    ports:
      - 7357:8000
    volumes:
      - ./:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


